export const metadata = {
  title: "Productos",
  description: "Generated by create next app",
};

const serverComponent = async () => {
  const resp = await fetch("https://fakestoreapi.com/products");
  const products = await resp.json();

  return (
    <div
      style={{
        display: "grid",
        gridTemplateColumns: "repeat(auto-fill, minmax(250px,1fr))",
        gap: "1rem",
        padding: "2rem",
      }}
    >
      {products.map((p) => {
        return (
          <div
            style={{
              border: "1px solid #ddd",
              borderRadius: "8px",
              padding: "1rem",
              backround: "#fff",
              boxShadow: "0 2px 8px",
            }}
          >
            <img
              src={p.image}
              alt={p.title}
              style={{ width: "100%", height: "200px", objectFit: "contain" }}
            />

            <h3
              style={{
                fontSize: "1.1rem",
                marginTop: "1rem",
                fontWeight: "600",
                color: "#fff",
              }}
            >
              {p.title}
            </h3>

            <p
              style={{
                fontSize: "1.1rem",
                marginTop: "1rem",
                fontWeight: "600",
                color: "#fff",
              }}
            >
              {p.price}
            </p>
          </div>
        );
      })}
    </div>
  );
};

export default serverComponent;
